<?php

function lightupthemap_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // get the form id
  // drupal_set_message($form_id);

  // for node ligth add form only
  if ($form_id == 'node_light_form') {

    // spit out the $form object
    // comment below, but devel, and devel kint modules must be enabled
    // kint($form);

    $form['field_senator_text']['widget']['0']['#default_value'] = 'this is the senator';
    $form['field_representative_text']['widget']['0']['#default_value'] = "this is the representative";
  }
}